class_name ArtManifest
extends RefCounted

const SPRITES := {
	"por_ely": "art/por_ely.png",
	"por_rex": "art/por_rex.png",
	"por_host": "art/por_host.png",
	"por_nahum": "art/por_nahum.png",
	"por_tuman": "art/por_tuman.png",
	"por_kirin": "art/por_kirin.png",
	"por_const": "art/por_const.png",
	"npc2_rhasa": "art/npc2_rhasa.png",
	"npcb_rhasa": "art/npcb_rhasa.png",
	"por_rhasa": "art/por_rhasa.png",
	"npc2_neva": "art/npc2_neva.png",
	"npcb_neva": "art/npcb_neva.png",
	"por_neva": "art/por_neva.png",
	"npc2_saphire": "art/npc2_saphire.png",
	"npcb_saphire": "art/npcb_saphire.png",
	"por_saphire": "art/por_saphire.png",
	"npc2_vane": "art/npc2_vane.png",
	"npcb_vane": "art/npcb_vane.png",
	"por_vane": "art/por_vane.png",
	"t2_hub_0": "art/t2_hub_0.png",
	"t2_hub_1": "art/t2_hub_1.png",
	"t2_hub_2": "art/t2_hub_2.png",
	"t2_0_0": "art/t2_0_0.png",
	"t2_0_1": "art/t2_0_1.png",
	"t2_0_2": "art/t2_0_2.png",
	"t2_1_0": "art/t2_1_0.png",
	"t2_1_1": "art/t2_1_1.png",
	"t2_1_2": "art/t2_1_2.png",
	"t2_2_0": "art/t2_2_0.png",
	"t2_2_1": "art/t2_2_1.png",
	"t2_2_2": "art/t2_2_2.png",
	"t2_3_0": "art/t2_3_0.png",
	"t2_3_1": "art/t2_3_1.png",
	"t2_3_2": "art/t2_3_2.png",
	"w2_hub": "art/w2_hub.png",
	"w2_0": "art/w2_0.png",
	"w2_1": "art/w2_1.png",
	"w2_2": "art/w2_2.png",
	"w2_3": "art/w2_3.png",
	"door2": "art/door2.png",
	"door_open": "art/door_open.png",
	"gate2": "art/gate2.png",
	"gate_open": "art/gate_open.png",
	"portal": "art/portal.png",
	"rock": "art/rock.png",
	"bones": "art/bones.png",
	"crate": "art/crate.png",
	"pod": "art/pod.png",
	"crystal": "art/crystal.png",
	"vent": "art/vent.png",
	"vat": "art/vat.png",
	"wreck": "art/wreck.png",
	"pillar": "art/pillar.png",
	"statue": "art/statue.png",
	"banner": "art/banner.png",
	"tree": "art/tree.png",
	"shrub": "art/shrub.png",
	"tent": "art/tent.png",
	"medic": "art/medic.png",
	"campfire": "art/campfire.png",
	"dec_stain_0": "art/dec_stain_0.png",
	"dec_stain_1": "art/dec_stain_1.png",
	"dec_stain_2": "art/dec_stain_2.png",
	"dec_stain_3": "art/dec_stain_3.png",
	"dec_bones_0": "art/dec_bones_0.png",
	"dec_bones_1": "art/dec_bones_1.png",
	"dec_bones_2": "art/dec_bones_2.png",
	"dec_crack_0": "art/dec_crack_0.png",
	"dec_tuft_0": "art/dec_tuft_0.png",
	"dec_vein_0": "art/dec_vein_0.png",
	"ico_frag": "art/ico_frag.png",
	"ico_heal": "art/ico_heal.png",
	"ico_boon": "art/ico_boon.png",
	"ico_exit": "art/ico_exit.png",
	"icn_dash": "art/icn_dash.png",
	"icn_skull": "art/icn_skull.png",
	"icn_crown": "art/icn_crown.png",
	"icn_rhasa": "art/icn_rhasa.png",
	"icn_neva": "art/icn_neva.png",
	"icn_saphire": "art/icn_saphire.png",
	"icn_rex": "art/icn_rex.png",
	"icn_kovan": "art/icn_kovan.png",
	"icn_upg_hp": "art/icn_upg_hp.png",
	"icn_upg_dmg": "art/icn_upg_dmg.png",
	"icn_upg_dash": "art/icn_upg_dash.png",
	"icn_upg_revive": "art/icn_upg_revive.png",
	"icn_upg_frag": "art/icn_upg_frag.png",
	"icn_upg_shield": "art/icn_upg_shield.png",
	"icn_stance_cleave": "art/icn_stance_cleave.png",
	"icn_stance_duel": "art/icn_stance_duel.png",
	"proj_0": "art/proj_0.png",
	"proj_1": "art/proj_1.png",
	"proj_2": "art/proj_2.png",
	# hub NPCs built from the concept-art sets (2-frame idle bob)
	"npc2_david": "art/c_david_idle_0.png",
	"npcb_david": "art/c_david_idle_1.png",
	"por_david": "art/por_c_david.png",
	"npc2_zirkon": "art/c_zirkon_idle_0.png",
	"npcb_zirkon": "art/c_zirkon_idle_1.png",
	"por_zirkon": "art/por_c_zirkon.png",
}

const FRAMES := {
	"ely": {"idle": ["art/ely_idle_0.png", "art/ely_idle_1.png"], "run": ["art/ely_run_0.png", "art/ely_run_1.png", "art/ely_run_2.png", "art/ely_run_3.png"], "atk1": ["art/ely_atk1_0.png"], "atk2": ["art/ely_atk2_0.png"], "atk3": ["art/ely_atk3_0.png"], "dash": ["art/ely_dash_0.png"], "parry": ["art/ely_parry_0.png"], "charge": ["art/ely_charge_0.png"], "hurt": ["art/ely_hurt_0.png"], "die": ["art/ely_die_0.png", "art/ely_die_1.png", "art/ely_die_2.png"], },
	"husk": {"idle": ["art/husk_idle_0.png", "art/husk_idle_1.png"], "windup": ["art/husk_windup_0.png"], "strike": ["art/husk_strike_0.png"], "hurt": ["art/husk_hurt_0.png"], "die": ["art/husk_die_0.png", "art/husk_die_1.png", "art/husk_die_2.png"], },
	"husk_1": {"idle": ["art/husk_1_idle_0.png", "art/husk_1_idle_1.png"], "windup": ["art/husk_1_windup_0.png"], "strike": ["art/husk_1_strike_0.png"], "hurt": ["art/husk_1_hurt_0.png"], "die": ["art/husk_1_die_0.png", "art/husk_1_die_1.png", "art/husk_1_die_2.png"], },
	"husk_2": {"idle": ["art/husk_2_idle_0.png", "art/husk_2_idle_1.png"], "windup": ["art/husk_2_windup_0.png"], "strike": ["art/husk_2_strike_0.png"], "hurt": ["art/husk_2_hurt_0.png"], "die": ["art/husk_2_die_0.png", "art/husk_2_die_1.png", "art/husk_2_die_2.png"], },
	"husk_3": {"idle": ["art/husk_3_idle_0.png", "art/husk_3_idle_1.png"], "windup": ["art/husk_3_windup_0.png"], "strike": ["art/husk_3_strike_0.png"], "hurt": ["art/husk_3_hurt_0.png"], "die": ["art/husk_3_die_0.png", "art/husk_3_die_1.png", "art/husk_3_die_2.png"], },
	"spitter": {"idle": ["art/spitter_idle_0.png", "art/spitter_idle_1.png"], "windup": ["art/spitter_windup_0.png"], "strike": ["art/spitter_strike_0.png"], "hurt": ["art/spitter_hurt_0.png"], "die": ["art/spitter_die_0.png", "art/spitter_die_1.png", "art/spitter_die_2.png"], },
	"spitter_1": {"idle": ["art/spitter_1_idle_0.png", "art/spitter_1_idle_1.png"], "windup": ["art/spitter_1_windup_0.png"], "strike": ["art/spitter_1_strike_0.png"], "hurt": ["art/spitter_1_hurt_0.png"], "die": ["art/spitter_1_die_0.png", "art/spitter_1_die_1.png", "art/spitter_1_die_2.png"], },
	"spitter_2": {"idle": ["art/spitter_2_idle_0.png", "art/spitter_2_idle_1.png"], "windup": ["art/spitter_2_windup_0.png"], "strike": ["art/spitter_2_strike_0.png"], "hurt": ["art/spitter_2_hurt_0.png"], "die": ["art/spitter_2_die_0.png", "art/spitter_2_die_1.png", "art/spitter_2_die_2.png"], },
	"spitter_3": {"idle": ["art/spitter_3_idle_0.png", "art/spitter_3_idle_1.png"], "windup": ["art/spitter_3_windup_0.png"], "strike": ["art/spitter_3_strike_0.png"], "hurt": ["art/spitter_3_hurt_0.png"], "die": ["art/spitter_3_die_0.png", "art/spitter_3_die_1.png", "art/spitter_3_die_2.png"], },
	"turret": {"idle": ["art/turret_idle_0.png", "art/turret_idle_1.png"], "windup": ["art/turret_windup_0.png"], "strike": ["art/turret_strike_0.png"], "hurt": ["art/turret_hurt_0.png"], "die": ["art/turret_die_0.png", "art/turret_die_1.png", "art/turret_die_2.png"], },
	"turret_1": {"idle": ["art/turret_1_idle_0.png", "art/turret_1_idle_1.png"], "windup": ["art/turret_1_windup_0.png"], "strike": ["art/turret_1_strike_0.png"], "hurt": ["art/turret_1_hurt_0.png"], "die": ["art/turret_1_die_0.png", "art/turret_1_die_1.png", "art/turret_1_die_2.png"], },
	"turret_2": {"idle": ["art/turret_2_idle_0.png", "art/turret_2_idle_1.png"], "windup": ["art/turret_2_windup_0.png"], "strike": ["art/turret_2_strike_0.png"], "hurt": ["art/turret_2_hurt_0.png"], "die": ["art/turret_2_die_0.png", "art/turret_2_die_1.png", "art/turret_2_die_2.png"], },
	"turret_3": {"idle": ["art/turret_3_idle_0.png", "art/turret_3_idle_1.png"], "windup": ["art/turret_3_windup_0.png"], "strike": ["art/turret_3_strike_0.png"], "hurt": ["art/turret_3_hurt_0.png"], "die": ["art/turret_3_die_0.png", "art/turret_3_die_1.png", "art/turret_3_die_2.png"], },
	"drone": {"idle": ["art/drone_idle_0.png", "art/drone_idle_1.png"], "windup": ["art/drone_windup_0.png"], "strike": ["art/drone_strike_0.png"], "hurt": ["art/drone_hurt_0.png"], "die": ["art/drone_die_0.png", "art/drone_die_1.png", "art/drone_die_2.png"], },
	"drone_1": {"idle": ["art/drone_1_idle_0.png", "art/drone_1_idle_1.png"], "windup": ["art/drone_1_windup_0.png"], "strike": ["art/drone_1_strike_0.png"], "hurt": ["art/drone_1_hurt_0.png"], "die": ["art/drone_1_die_0.png", "art/drone_1_die_1.png", "art/drone_1_die_2.png"], },
	"drone_2": {"idle": ["art/drone_2_idle_0.png", "art/drone_2_idle_1.png"], "windup": ["art/drone_2_windup_0.png"], "strike": ["art/drone_2_strike_0.png"], "hurt": ["art/drone_2_hurt_0.png"], "die": ["art/drone_2_die_0.png", "art/drone_2_die_1.png", "art/drone_2_die_2.png"], },
	"drone_3": {"idle": ["art/drone_3_idle_0.png", "art/drone_3_idle_1.png"], "windup": ["art/drone_3_windup_0.png"], "strike": ["art/drone_3_strike_0.png"], "hurt": ["art/drone_3_hurt_0.png"], "die": ["art/drone_3_die_0.png", "art/drone_3_die_1.png", "art/drone_3_die_2.png"], },
	"sentinel": {"idle": ["art/sentinel_idle_0.png", "art/sentinel_idle_1.png"], "windup": ["art/sentinel_windup_0.png"], "strike": ["art/sentinel_strike_0.png"], "hurt": ["art/sentinel_hurt_0.png"], "die": ["art/sentinel_die_0.png", "art/sentinel_die_1.png", "art/sentinel_die_2.png"], },
	"sentinel_1": {"idle": ["art/sentinel_1_idle_0.png", "art/sentinel_1_idle_1.png"], "windup": ["art/sentinel_1_windup_0.png"], "strike": ["art/sentinel_1_strike_0.png"], "hurt": ["art/sentinel_1_hurt_0.png"], "die": ["art/sentinel_1_die_0.png", "art/sentinel_1_die_1.png", "art/sentinel_1_die_2.png"], },
	"sentinel_2": {"idle": ["art/sentinel_2_idle_0.png", "art/sentinel_2_idle_1.png"], "windup": ["art/sentinel_2_windup_0.png"], "strike": ["art/sentinel_2_strike_0.png"], "hurt": ["art/sentinel_2_hurt_0.png"], "die": ["art/sentinel_2_die_0.png", "art/sentinel_2_die_1.png", "art/sentinel_2_die_2.png"], },
	"sentinel_3": {"idle": ["art/sentinel_3_idle_0.png", "art/sentinel_3_idle_1.png"], "windup": ["art/sentinel_3_windup_0.png"], "strike": ["art/sentinel_3_strike_0.png"], "hurt": ["art/sentinel_3_hurt_0.png"], "die": ["art/sentinel_3_die_0.png", "art/sentinel_3_die_1.png", "art/sentinel_3_die_2.png"], },
	"rex": {"idle": ["art/rex_idle_0.png", "art/rex_idle_1.png"], "atk": ["art/rex_atk_0.png"], "p2": ["art/rex_p2_0.png"], "hurt": ["art/rex_hurt_0.png"], "die": ["art/rex_die_0.png", "art/rex_die_1.png", "art/rex_die_2.png"], },
	"host": {"idle": ["art/host_idle_0.png", "art/host_idle_1.png"], "atk": ["art/host_atk_0.png"], "p2": ["art/host_p2_0.png"], "hurt": ["art/host_hurt_0.png"], "die": ["art/host_die_0.png", "art/host_die_1.png", "art/host_die_2.png"], },
	"nahum": {"idle": ["art/nahum_idle_0.png", "art/nahum_idle_1.png"], "atk": ["art/nahum_atk_0.png"], "p2": ["art/nahum_p2_0.png"], "hurt": ["art/nahum_hurt_0.png"], "die": ["art/nahum_die_0.png", "art/nahum_die_1.png", "art/nahum_die_2.png"], },
	"tuman": {"idle": ["art/tuman_idle_0.png", "art/tuman_idle_1.png"], "atk": ["art/tuman_atk_0.png"], "p2": ["art/tuman_p2_0.png"], "hurt": ["art/tuman_hurt_0.png"], "die": ["art/tuman_die_0.png", "art/tuman_die_1.png", "art/tuman_die_2.png"], },
	"kirin": {"idle": ["art/kirin_idle_0.png", "art/kirin_idle_1.png"], "atk": ["art/kirin_atk_0.png"], "p2": ["art/kirin_p2_0.png"], "hurt": ["art/kirin_hurt_0.png"], "die": ["art/kirin_die_0.png", "art/kirin_die_1.png", "art/kirin_die_2.png"], },
	"const": {"idle": ["art/const_idle_0.png", "art/const_idle_1.png"], "atk": ["art/const_atk_0.png"], "p2": ["art/const_p2_0.png"], "hurt": ["art/const_hurt_0.png"], "die": ["art/const_die_0.png", "art/const_die_1.png", "art/const_die_2.png"], },
}
